# Generated by Django 5.0.4 on 2024-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='otp_gen_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
