# Generated by Django 5.0.4 on 2024-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_img_alter_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
