# Generated by Django 5.0.4 on 2024-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_otp_gen_time_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pronouns',
            field=models.CharField(blank=True, default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
