# Generated by Django 5.0.4 on 2024-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
