# Generated by Django 5.0.4 on 2024-07-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_category_id_delete_blogcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claps',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='home.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.blog'),
        ),
    ]
