# Generated by Django 5.0.4 on 2024-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articleread'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
