# Generated by Django 5.0.4 on 2024-12-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_article_created_at_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleread',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
